spirit/admin/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import include, url

from . import views
import spirit.category.admin.urls
import spirit.comment.flag.admin.urls
import spirit.topic.admin.urls
import spirit.user.admin.urls


urlpatterns = [
    url(r'^$', views.dashboard, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^config/$', views.config_basic, name='config-basic'),

    url(r'^category/', include(spirit.category.admin.urls, namespace='category')),
    url(r'^comment/flag/', include(spirit.comment.flag.admin.urls, namespace='flag')),
    url(r'^topic/', include(spirit.topic.admin.urls, namespace='topic')),
    url(r'^user/', include(spirit.user.admin.urls, namespace='user')),
]

spirit/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import include, url

import spirit.topic.views
import spirit.admin.urls
import spirit.user.urls
import spirit.search.urls
import spirit.category.urls
import spirit.topic.urls
import spirit.comment.urls


patterns = [
    url(r'^$', spirit.topic.views.index_active, name='index'),
    url(r'^st/admin/', include(spirit.admin.urls, namespace='admin')),
    url(r'^user/', include(spirit.user.urls, namespace='user')),
    url(r'^search/', include(spirit.search.urls, namespace='search')),
    url(r'^category/', include(spirit.category.urls, namespace='category')),
    url(r'^topic/', include(spirit.topic.urls, namespace='topic')),
    url(r'^comment/', include(spirit.comment.urls, namespace='comment')),
]


urlpatterns = [
    url(r'^', include(patterns, namespace='spirit', app_name='spirit')),
]

spirit/user/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url, include

from .auth import urls as auth_urls
from . import views


urlpatterns = [
    url(r'^$', views.update, name='update'),
    url(r'^password-change/$', views.password_change, name='password-change'),
    url(r'^email-change/$', views.email_change, name='email-change'),
    url(r'^email-change/(?P<token>[0-9A-Za-z_\-\.]+)/$', views.email_change_confirm, name='email-change-confirm'),

    url(r'^(?P<pk>\d+)/$', views.comments, kwargs={'slug': "", }, name='detail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.comments, name='detail'),

    url(r'^topics/(?P<pk>\d+)/$', views.topics, kwargs={'slug': "", }, name='topics'),
    url(r'^topics/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.topics, name='topics'),

    url(r'^likes/(?P<pk>\d+)/$', views.likes, kwargs={'slug': "", }, name='likes'),
    url(r'^likes/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.likes, name='likes'),

    url(r'^menu/$', views.menu, name='menu'),

    url(r'^', include(auth_urls, namespace='auth')),
]

user/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', 'user.views.view_event_in_profile', kwargs={'slug': "", }, name='view_event_in_profile'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/events/$', 'user.views.view_event_in_profile', name="view_event_in_profile"),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/event_gesuche/$', 'user.views.view_support_in_profile', name="view_support_in_profile"),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/event_gesuche_angebote/$', 'user.views.view_offer_in_profile', name="view_offer_in_profile"),

    # url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/angebotene_fahrten/$', 'user.views.view_transportation_in_profile', name="view_transportation_in_profile"),
    # url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/angefragte_fahrten/$', 'user.views.view_transportation_requests_in_profile', name="view_transportation_requests_in_profile"),

    ]

spirit/category/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.conf import settings

from .managers import CategoryQuerySet
from ..core.utils.models import AutoSlugField


class Category(models.Model):

    parent = models.ForeignKey('self', verbose_name=_("category parent"), null=True, blank=True)

    title = models.CharField(_("title"), max_length=75)
    slug = AutoSlugField(populate_from="title", db_index=False, blank=True)
    description = models.CharField(_("description"), max_length=255, blank=True)
    is_global = models.BooleanField(_("global"), default=True,
                                    help_text=_('Designates whether the topics will be'
                                                'displayed in the all-categories list.'))
    is_closed = models.BooleanField(_("closed"), default=False)
    is_removed = models.BooleanField(_("removed"), default=False)
    is_private = models.BooleanField(_("private"), default=False)

    # topic_count = models.PositiveIntegerField(_("topic count"), default=0)

    objects = CategoryQuerySet.as_manager()

    class Meta:
        ordering = ['title', 'pk']
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def get_absolute_url(self):
        if self.pk == settings.ST_TOPIC_PRIVATE_CATEGORY_PK:
            return reverse('spirit:topic:private:index')
        else:
            return reverse('spirit:category:detail', kwargs={'pk': str(self.id), 'slug': self.slug})

    @property
    def is_subcategory(self):
        if self.parent_id:
            return True
        else:
            return False


# def topic_posted_handler(sender, topic, **kwargs):
#    if topic.category.is_subcategory:
#        category = Category.objects.filter(pk__in=[topic.category.pk, topic.category.parent.pk])
#    else:
#        category = Category.objects.filter(pk=topic.category.pk)
#
#    category.update(topic_count=F('topic_count') + 1)


# topic_posted.connect(topic_posted_handler, dispatch_uid=__name__)

spirit/comment/bookmark/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from djconfig import config

from ...core.utils import paginator


class CommentBookmark(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_bookmarks')
    topic = models.ForeignKey('spirit_topic.Topic')

    comment_number = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('user', 'topic')
        verbose_name = _("comment bookmark")
        verbose_name_plural = _("comments bookmarks")

    def _get_url(self, comment_number=None):
        comment_number = comment_number or self.comment_number
        return paginator.get_url(
            url=self.topic.get_absolute_url(),
            obj_number=comment_number,
            per_page=config.comments_per_page,
            page_var='page'
        )

    def get_absolute_url(self):
        return self._get_url()

    def get_new_comment_url(self):
        comment_number = self.comment_number + 1
        return self._get_url(comment_number=comment_number)

    @staticmethod
    def page_to_comment_number(page_number):
        try:
            page_number = int(page_number)
        except ValueError:
            return

        return config.comments_per_page * (page_number - 1) + 1

    @classmethod
    def update_or_create(cls, user, topic, comment_number):
        if not user.is_authenticated():
            return

        if comment_number is None:
            return

        bookmark, created = cls.objects.update_or_create(
            user=user,
            topic=topic,
            defaults={'comment_number': comment_number, }
        )

        return bookmark

spirit/comment/flag/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils import timezone


REASON_CHOICES = (
    (0, _("Spam")),
    (1, _("Other")),
)


class CommentFlag(models.Model):

    moderator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_flags',
                                  null=True, blank=True)
    comment = models.OneToOneField('spirit_comment.Comment')

    date = models.DateTimeField(default=timezone.now)
    is_closed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment flag")
        verbose_name_plural = _("comments flags")

    # def get_absolute_url(self):
        # pass


class Flag(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_flags')
    comment = models.ForeignKey('spirit_comment.Comment')

    date = models.DateTimeField(default=timezone.now)
    reason = models.IntegerField(_("reason"), choices=REASON_CHOICES)
    body = models.TextField(_("body"), blank=True)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("flag")
        verbose_name_plural = _("flags")

spirit/comment/history/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import timezone


class CommentHistory(models.Model):

    comment_fk = models.ForeignKey('spirit_comment.Comment', verbose_name=_("original comment"))

    comment_html = models.TextField(_("comment html"))
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment history")
        verbose_name_plural = _("comments history")

    def get_absolute_url(self):
        return reverse('spirit:comment:history:detail', kwargs={'pk': str(self.id), })

    @classmethod
    def create(cls, comment, created_at=None):
        created_at = created_at or timezone.now()

        return cls.objects.create(
            comment_fk=comment,
            comment_html=comment.comment_html,
            date=created_at
        )

    @classmethod
    def create_maybe(cls, comment):
        exists = cls.objects\
            .filter(comment_fk=comment)\
            .exists()

        if not exists:
            return cls.create(comment, created_at=comment.date)

spirit/comment/like/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import timezone


class CommentLike(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_likes')
    comment = models.ForeignKey('spirit_comment.Comment', related_name='comment_likes')

    date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("like")
        verbose_name_plural = _("likes")

    def get_delete_url(self):
        return reverse('spirit:comment:like:delete', kwargs={'pk': str(self.pk), })

spirit/comment/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models import F
from django.utils import timezone

from .managers import CommentQuerySet


COMMENT_MAX_LEN = 6000  # changing this needs migration

COMMENT, MOVED, CLOSED, UNCLOSED, PINNED, UNPINNED = range(6)

ACTION = (
    (COMMENT, _("comment")),
    (MOVED, _("topic moved")),
    (CLOSED, _("topic closed")),
    (UNCLOSED, _("topic unclosed")),
    (PINNED, _("topic pinned")),
    (UNPINNED, _("topic unpinned")),
)


class Comment(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comments')
    topic = models.ForeignKey('spirit_topic.Topic')

    comment = models.TextField(_("comment"), max_length=COMMENT_MAX_LEN)
    comment_html = models.TextField(_("comment html"))
    action = models.IntegerField(_("action"), choices=ACTION, default=COMMENT)
    date = models.DateTimeField(default=timezone.now)
    is_removed = models.BooleanField(default=False)
    is_modified = models.BooleanField(default=False)
    ip_address = models.GenericIPAddressField(blank=True, null=True)

    modified_count = models.PositiveIntegerField(_("modified count"), default=0)
    likes_count = models.PositiveIntegerField(_("likes count"), default=0)

    objects = CommentQuerySet.as_manager()

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment")
        verbose_name_plural = _("comments")

    def get_absolute_url(self):
        return reverse('spirit:comment:find', kwargs={'pk': str(self.id), })

    @property
    def like(self):
        # *likes* is dynamically created by manager.with_likes()
        try:
            assert len(self.likes) <= 1, "Panic, too many likes"
            return self.likes[0]
        except (AttributeError, IndexError):
            return

    def increase_modified_count(self):
        Comment.objects\
            .filter(pk=self.pk)\
            .update(modified_count=F('modified_count') + 1)

    def increase_likes_count(self):
        Comment.objects\
            .filter(pk=self.pk)\
            .update(likes_count=F('likes_count') + 1)

    def decrease_likes_count(self):
        Comment.objects\
            .filter(pk=self.pk, likes_count__gt=0)\
            .update(likes_count=F('likes_count') - 1)

    @classmethod
    def create_moderation_action(cls, user, topic, action):
        # TODO: better comment_html text (map to actions), use default language
        return cls.objects.create(
            user=user,
            topic=topic,
            action=action,
            comment="action",
            comment_html="action"
        )

user/models.py
from django.db import models

# Create your models here.

spirit/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from djconfig.forms import ConfigForm


class BasicConfigForm(ConfigForm):

    site_name = forms.CharField(initial="Spirit", label=_("site name"))
    site_description = forms.CharField(initial="", label=_("site description"), max_length=75, required=False)
    template_footer = forms.CharField(initial="", label=_("footer snippet"), required=False,
                                      widget=forms.Textarea(attrs={'rows': 2, }),
                                      help_text=_("This gets rendered just before the footer in your template."))
    comments_per_page = forms.IntegerField(initial=20, label=_("comments per page"), min_value=1, max_value=100)
    topics_per_page = forms.IntegerField(initial=20, label=_("topics per page"), min_value=1, max_value=100)

spirit/category/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import smart_text

from ..models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ("parent", "title", "description", "is_global", "is_closed", "is_removed")

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        queryset = Category.objects.visible().parents()

        if self.instance.pk:
            queryset = queryset.exclude(pk=self.instance.pk)

        self.fields['parent'] = forms.ModelChoiceField(queryset=queryset, required=False)
        self.fields['parent'].label_from_instance = lambda obj: smart_text(obj.title)

    def clean_parent(self):
        parent = self.cleaned_data["parent"]

        if self.instance.pk:
            has_childrens = self.instance.category_set.all().exists()

            if parent and has_childrens:
                raise forms.ValidationError(_("The category you are updating "
                                              "can not have a parent since it has childrens"))

        return parent

spirit/comment/bookmark/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms

from .models import CommentBookmark


class BookmarkForm(forms.ModelForm):

    class Meta:
        model = CommentBookmark
        fields = ['comment_number', ]

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super(BookmarkForm, self).__init__(*args, **kwargs)
        self.user = user
        self.topic = topic

    def save(self, commit=True):
        comment_number = self.cleaned_data['comment_number']

        # Bookmark is created/updated on topic view.
        CommentBookmark.objects\
            .filter(user=self.user, topic=self.topic)\
            .update(comment_number=comment_number)

spirit/comment/flag/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms

from ..models import CommentFlag


class CommentFlagForm(forms.ModelForm):

    class Meta:
        model = CommentFlag
        fields = ("is_closed", )

    def __init__(self, user=None, *args, **kwargs):
        super(CommentFlagForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        self.instance.moderator = self.user
        return super(CommentFlagForm, self).save(commit)

spirit/user/templates/spirit/user/_profile.html
{% load spirit_tags i18n %}


    <div class="profile-img">
		<img class="profile-avatar" src="{% get_gravatar_url user=p_user size=200 %}" />
		<div class="profile-username">{{ p_user.username }}</div>
	</div>

    <div class="profile-info">
		<ul class="profile-track">
			<li>
				<div class="profile-title">{% trans "Joined at" %}</div>
				<div class="profile-date">{{ p_user.date_joined|shortnaturaltime }}</div>
			</li><!--
		 --><li>
				<div class="profile-title">{% trans "Seen" %}</div>
				<div class="profile-date">{{ p_user.st.last_seen|shortnaturaltime }}</div>
			</li>

            {% if user.st.is_administrator %}
                <li>
                    <div class="profile-title">{% trans "Last IP" %}</div>
                    <div class="profile-date">{{ p_user.st.last_ip }}</div>
                </li>
            {% endif %}
		</ul>
	</div>

    {% ifequal user.username p_user.username %}
        <div class="profile-preferences">
            <a class="button" href="{% url "spirit:user:update" %}"><i class="fa fa-cog"></i> {% trans "Preferences" %}</a>
        </div>
    {% else %}
        <div class="private-message">
            <a class="button" href="{% url "spirit:topic:private:publish" user_id=p_user.pk %}"><i class="fa fa-envelope"></i> {% trans "Private Message" %}</a>
        </div>
    {% endifequal %}

    {% if user.st.is_administrator %}
        <div class="profile-preferences">
            <a class="button" href="{% url "spirit:admin:user:edit" user_id=p_user.pk %}"><i class="fa fa-cog"></i> {% trans "Edit user" %}</a>
        </div>
    {% endif %}
    <h3>Forum</h3>
    <ul class="tabs">
		<li><a class="tab-link{% ifequal active_tab 0 %} is-selected{% endifequal %}" href="{% url "spirit:user:detail" pk=p_user.pk slug=p_user.st.slug %}" >{% trans "Comments" %}</a></li><!--
	 --><li><a class="tab-link{% ifequal active_tab 1 %} is-selected{% endifequal %}" href="{% url "spirit:user:topics" pk=p_user.pk slug=p_user.st.slug %}" >{% trans "Topics" %}</a></li><!--
	 --><li><a class="tab-link{% ifequal active_tab 2 %} is-selected{% endifequal %}" href="{% url "spirit:user:likes" pk=p_user.pk slug=p_user.st.slug %}" >{% trans "Likes" %}</a></li>
        <li><a class="tab-link" href="{% url "user:view_event_in_profile" pk=p_user.pk slug=p_user.st.slug %}" style="color: #89B267"><strong>Event Aktivitäten</strong></a></li>
        <li><a class="tab-link" href="http://ttip-demo.de/anreise/" style="color: #89B267"><strong>Mitfahrbörse</strong></a></li>
	</ul>

spirit/user/templates/spirit/user/_render_comments_list.html
{% load spirit_tags i18n %}

    <div class="comments">

        {% for c in comments %}

            <div class="comment">

                <div class="comment-media">
                    <div class="comment-img">
                        <img class="comment-avatar" src="{% get_gravatar_url user=c.user size=50 %}" />
                    </div>

                    <div class="comment-body">
                        <div class="comment-info">

                            <div class="comment-username">
                                <a href="{{ c.user.st.get_absolute_url }}">{{ c.user.username }}</a>
                            </div>

                            <ul class="comment-date">
                                <li><a href="{{ c.get_absolute_url }}"><i class="fa fa-comments"></i> {{ c.topic.title }}</a></li><!--
			                 --><li title="{{ c.date }}">{{ c.date|shortnaturaltime }}</li>
                            </ul>

                        </div>

                        <div class="comment-text">
                            {% post_render_comment comment=c %}
                        </div>
                    </div>
                </div>
            </div>

        {% empty %}
            <p>{% trans "There are no comments here, yet" %}</p>
        {% endfor %}

    </div>


    <script>

	$( document ).ready(function() {

        hljs.initHighlightingOnLoad();

	});

	</script>

spirit/user/templates/spirit/user/activation_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans trimmed %}You're receiving this email because you registered at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following link to activate your account:" %}

{{ protocol }}://{{ domain }}{% url 'spirit:user:auth:registration-activation' pk=user_id token=token %}

    Bitte beachte, dass keine Benachrichtigungsmails versand werden, wenn es Änderungen bei Fahrten oder Events gibt.

{% trans "Thanks for using our site!" %}

{% endautoescape %}

spirit/user/templates/spirit/user/email_change_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans trimmed %}You're receiving this because you changed your user email at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following link to confirm your email change:" %}

{{ protocol }}://{{ domain }}{% url 'spirit:user:email-change-confirm' token=token %}

{% trans "Thanks for using our site!" %}

{% endautoescape %}

spirit/user/templates/spirit/user/menu.html
{# todo: remove this, use :target on menu #}

{% extends "spirit/_base.html" %}

{% load i18n %}

{% block title %}{% trans "User menu" %}{% endblock %}

{% block content %}

    <h1 class="headline">{% trans "Menu" %}</h1>

    <ul class="menu">
         <li><a class="menu-link" href="{% url "spirit:user:detail" pk=user.pk slug=user.st.slug %}">{% trans "Profile" %}</a></li>
         <li><a class="menu-link" href="{% url "spirit:topic:index-active" %}">{% trans "Topics" %}</a></li>
         <li><a class="menu-link" href="{% url "spirit:topic:unread:index" %}">{% trans "Unread topics" %}</a></li>
         <li><a class="menu-link" href="{% url "spirit:topic:private:index" %}">{% trans "Private topics" %}</a></li>

        {% if user.st.is_administrator %}
            <li><a class="menu-link" href="{% url "spirit:admin:index" %}">{% trans "Admin" %}</a></li>
        {% endif %}

         <li><a class="menu-link js-post" href="{% url "spirit:user:auth:logout" %}">{% trans "Log out" %}</a></li>
    </ul>

{% endblock %}

spirit/user/templates/spirit/user/notification_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans trimmed %}You have a new notification at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following link to read the comment:" %}

{{ protocol }}://{{ domain }}{% url "spirit:comment:bookmark:find" topic_id=comment.topic_id %}

{% trans "If you don't want to keep receiving notifications, you can deactivate them on your profile preferences." %}

{% endautoescape %}

spirit/user/templates/spirit/user/profile_comments.html
{% extends "spirit/_base.html" %}

{% load spirit_tags i18n tz %}

{% block title %}{{ p_user.username }} {% trans "comments" %}{% endblock %}

{% block content %}

    {% include "spirit/user/_profile.html" with active_tab=0 %}

    {% include "spirit/user/_render_comments_list.html" %}

    {% render_paginator comments %}

{% endblock %}

spirit/user/templates/spirit/user/profile_email_change.html
{% extends "spirit/_base.html" %}

{% load i18n %}

{% block title %}{% trans "Email change" %}{% endblock %}

{% block content %}

    <h1 class="headline">{% trans "Email change" %}</h1>

    <form action="." method="post">
        {% csrf_token %}
        {% include "spirit/_form.html" %}

        <input class="button" type="submit" name="post" value="{% trans 'Change my email' %}" />
    </form>

{% endblock %}

spirit/user/templates/spirit/user/profile_likes.html
{% extends "spirit/_base.html" %}

{% load spirit_tags i18n tz %}

{% block title %}{{ p_user.username }} {% trans "likes" %}{% endblock %}

{% block content %}

    {% include "spirit/user/_profile.html" with active_tab=2 %}

    {% include "spirit/user/_render_comments_list.html" %}

    {% render_paginator comments %}

{% endblock %}

spirit/user/templates/spirit/user/profile_password_change.html
{% extends "spirit/_base.html" %}

{% load i18n %}

{% block title %}{% trans "Password change" %}{% endblock %}

{% block content %}

    <h1 class="headline">{% trans "Password change" %}</h1>

    <form action="." method="post">
        {% csrf_token %}
        {% include "spirit/_form.html" %}

        <input class="button" type="submit" name="post" value="{% trans 'Change my password' %}" />
    </form>

{% endblock %}

spirit/user/templates/spirit/user/profile_topics.html
{% extends "spirit/_base.html" %}

{% load spirit_tags i18n %}

{% block title %}{{ p_user.username }} {% trans "topics" %}{% endblock %}

{% block content %}

    {% include "spirit/user/_profile.html" with active_tab=1 %}

    {% include "spirit/topic/_render_list.html" %}

    {% render_paginator topics %}

{% endblock %}

spirit/user/templates/spirit/user/profile_update.html
{% extends "spirit/_base.html" %}

{% load i18n %}

{% block title %}{% trans "Preferences" %}{% endblock %}

{% block content %}

    <h1 class="headline">{% trans "Preferences" %}</h1>

    <dl class="preference">
	   <dt class="preference-label">{% trans "Email" %}:</dt>
	   <dd class="preference-desc"><a href="{% url "spirit:user:email-change" %}"><i class="fa fa-pencil"></i> {{ user.email }}</a></dd>

	   <dt class="preference-label">{% trans "Password" %}:</dt>
	   <dd class="preference-desc"><a href="{% url "spirit:user:password-change" %}"><i class="fa fa-pencil"></i> {% trans "Change password" %}</a></dd>

	   <dt class="preference-label">{% trans "Avatar" %}:</dt>
	   <dd class="preference-desc"><a href="https://gravatar.com"><i class="fa fa-pencil"></i> {% trans "Change avatar" %}</a>
           ({% trans "Go to gravatar.com and use your current email to change it" %})</dd>
	</dl>

    <form action="." method="post">
        {% csrf_token %}
        {% include "spirit/_form.html" with form=uform %}
        {% include "spirit/_form.html" %}

        <input class="button" type="submit" name="post" value="{% trans "Save" %}" />
    </form>

{% endblock %}