spirit/admin/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import include, url

from . import views
import spirit.category.admin.urls
import spirit.comment.flag.admin.urls
import spirit.topic.admin.urls
import spirit.user.admin.urls


urlpatterns = [
    url(r'^$', views.dashboard, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^config/$', views.config_basic, name='config-basic'),

    url(r'^category/', include(spirit.category.admin.urls, namespace='category')),
    url(r'^comment/flag/', include(spirit.comment.flag.admin.urls, namespace='flag')),
    url(r'^topic/', include(spirit.topic.admin.urls, namespace='topic')),
    url(r'^user/', include(spirit.user.admin.urls, namespace='user')),
]

spirit/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import include, url

import spirit.topic.views
import spirit.admin.urls
import spirit.user.urls
import spirit.search.urls
import spirit.category.urls
import spirit.topic.urls
import spirit.comment.urls


patterns = [
    url(r'^$', spirit.topic.views.index_active, name='index'),
    url(r'^st/admin/', include(spirit.admin.urls, namespace='admin')),
    url(r'^user/', include(spirit.user.urls, namespace='user')),
    url(r'^search/', include(spirit.search.urls, namespace='search')),
    url(r'^category/', include(spirit.category.urls, namespace='category')),
    url(r'^topic/', include(spirit.topic.urls, namespace='topic')),
    url(r'^comment/', include(spirit.comment.urls, namespace='comment')),
]


urlpatterns = [
    url(r'^', include(patterns, namespace='spirit', app_name='spirit')),
]

spirit/user/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url, include

from .auth import urls as auth_urls
from . import views


urlpatterns = [
    url(r'^$', views.update, name='update'),
    url(r'^password-change/$', views.password_change, name='password-change'),
    url(r'^email-change/$', views.email_change, name='email-change'),
    url(r'^email-change/(?P<token>[0-9A-Za-z_\-\.]+)/$', views.email_change_confirm, name='email-change-confirm'),

    url(r'^(?P<pk>\d+)/$', views.comments, kwargs={'slug': "", }, name='detail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.comments, name='detail'),

    url(r'^topics/(?P<pk>\d+)/$', views.topics, kwargs={'slug': "", }, name='topics'),
    url(r'^topics/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.topics, name='topics'),

    url(r'^likes/(?P<pk>\d+)/$', views.likes, kwargs={'slug': "", }, name='likes'),
    url(r'^likes/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.likes, name='likes'),

    url(r'^menu/$', views.menu, name='menu'),

    url(r'^', include(auth_urls, namespace='auth')),
]

user/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', 'user.views.view_event_in_profile', kwargs={'slug': "", }, name='view_event_in_profile'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/events/$', 'user.views.view_event_in_profile', name="view_event_in_profile"),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/event_gesuche/$', 'user.views.view_support_in_profile', name="view_support_in_profile"),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/event_gesuche_angebote/$', 'user.views.view_offer_in_profile', name="view_offer_in_profile"),

    # url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/angebotene_fahrten/$', 'user.views.view_transportation_in_profile', name="view_transportation_in_profile"),
    # url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/angefragte_fahrten/$', 'user.views.view_transportation_requests_in_profile', name="view_transportation_requests_in_profile"),

    ]

spirit/category/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.conf import settings

from .managers import CategoryQuerySet
from ..core.utils.models import AutoSlugField


class Category(models.Model):

    parent = models.ForeignKey('self', verbose_name=_("category parent"), null=True, blank=True)

    title = models.CharField(_("title"), max_length=75)
    slug = AutoSlugField(populate_from="title", db_index=False, blank=True)
    description = models.CharField(_("description"), max_length=255, blank=True)
    is_global = models.BooleanField(_("global"), default=True,
                                    help_text=_('Designates whether the topics will be'
                                                'displayed in the all-categories list.'))
    is_closed = models.BooleanField(_("closed"), default=False)
    is_removed = models.BooleanField(_("removed"), default=False)
    is_private = models.BooleanField(_("private"), default=False)

    # topic_count = models.PositiveIntegerField(_("topic count"), default=0)

    objects = CategoryQuerySet.as_manager()

    class Meta:
        ordering = ['title', 'pk']
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def get_absolute_url(self):
        if self.pk == settings.ST_TOPIC_PRIVATE_CATEGORY_PK:
            return reverse('spirit:topic:private:index')
        else:
            return reverse('spirit:category:detail', kwargs={'pk': str(self.id), 'slug': self.slug})

    @property
    def is_subcategory(self):
        if self.parent_id:
            return True
        else:
            return False


# def topic_posted_handler(sender, topic, **kwargs):
#    if topic.category.is_subcategory:
#        category = Category.objects.filter(pk__in=[topic.category.pk, topic.category.parent.pk])
#    else:
#        category = Category.objects.filter(pk=topic.category.pk)
#
#    category.update(topic_count=F('topic_count') + 1)


# topic_posted.connect(topic_posted_handler, dispatch_uid=__name__)

spirit/comment/bookmark/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from djconfig import config

from ...core.utils import paginator


class CommentBookmark(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_bookmarks')
    topic = models.ForeignKey('spirit_topic.Topic')

    comment_number = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('user', 'topic')
        verbose_name = _("comment bookmark")
        verbose_name_plural = _("comments bookmarks")

    def _get_url(self, comment_number=None):
        comment_number = comment_number or self.comment_number
        return paginator.get_url(
            url=self.topic.get_absolute_url(),
            obj_number=comment_number,
            per_page=config.comments_per_page,
            page_var='page'
        )

    def get_absolute_url(self):
        return self._get_url()

    def get_new_comment_url(self):
        comment_number = self.comment_number + 1
        return self._get_url(comment_number=comment_number)

    @staticmethod
    def page_to_comment_number(page_number):
        try:
            page_number = int(page_number)
        except ValueError:
            return

        return config.comments_per_page * (page_number - 1) + 1

    @classmethod
    def update_or_create(cls, user, topic, comment_number):
        if not user.is_authenticated():
            return

        if comment_number is None:
            return

        bookmark, created = cls.objects.update_or_create(
            user=user,
            topic=topic,
            defaults={'comment_number': comment_number, }
        )

        return bookmark

spirit/comment/flag/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils import timezone


REASON_CHOICES = (
    (0, _("Spam")),
    (1, _("Other")),
)


class CommentFlag(models.Model):

    moderator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_flags',
                                  null=True, blank=True)
    comment = models.OneToOneField('spirit_comment.Comment')

    date = models.DateTimeField(default=timezone.now)
    is_closed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment flag")
        verbose_name_plural = _("comments flags")

    # def get_absolute_url(self):
        # pass


class Flag(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_flags')
    comment = models.ForeignKey('spirit_comment.Comment')

    date = models.DateTimeField(default=timezone.now)
    reason = models.IntegerField(_("reason"), choices=REASON_CHOICES)
    body = models.TextField(_("body"), blank=True)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("flag")
        verbose_name_plural = _("flags")

spirit/comment/history/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import timezone


class CommentHistory(models.Model):

    comment_fk = models.ForeignKey('spirit_comment.Comment', verbose_name=_("original comment"))

    comment_html = models.TextField(_("comment html"))
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment history")
        verbose_name_plural = _("comments history")

    def get_absolute_url(self):
        return reverse('spirit:comment:history:detail', kwargs={'pk': str(self.id), })

    @classmethod
    def create(cls, comment, created_at=None):
        created_at = created_at or timezone.now()

        return cls.objects.create(
            comment_fk=comment,
            comment_html=comment.comment_html,
            date=created_at
        )

    @classmethod
    def create_maybe(cls, comment):
        exists = cls.objects\
            .filter(comment_fk=comment)\
            .exists()

        if not exists:
            return cls.create(comment, created_at=comment.date)

spirit/comment/like/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import timezone


class CommentLike(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='st_comment_likes')
    comment = models.ForeignKey('spirit_comment.Comment', related_name='comment_likes')

    date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("like")
        verbose_name_plural = _("likes")

    def get_delete_url(self):
        return reverse('spirit:comment:like:delete', kwargs={'pk': str(self.pk), })

spirit/core/utils/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from slugify import slugify as unicode_slugify

from django.db.models.fields import SlugField
from django.utils.encoding import smart_text
from django.utils.text import slugify
from django.conf import settings

__all__ = ['AutoSlugField', ]


class AutoSlugField(SlugField):
    """
    Auto populates itself from another field.

    It behaves like a regular SlugField.
    When populate_from is provided it'll populate itself on creation,
    only if a slug was not provided.
    """

    def __init__(self, *args, **kwargs):
        self.populate_from = kwargs.pop('populate_from', None)
        super(AutoSlugField, self).__init__(*args, **kwargs)

    def pre_save(self, instance, add):
        default = super(AutoSlugField, self).pre_save(instance, add)

        if default or not add or not self.populate_from:
            return default

        inst = instance

        for attr in self.populate_from.split('.'):
            value = getattr(inst, attr)
            inst = value

        if value is None:
            return default

        # TODO: Django 1.9 will support unicode slugs
        if settings.ST_UNICODE_SLUGS:
            # TODO: mark as safe?
            slug = unicode_slugify(smart_text(value), ok='-')
        else:
            slug = slugify(smart_text(value))

        slug = slug[:self.max_length].strip('-')

        # Update the model’s attribute
        setattr(instance, self.attname, slug)

        return slug

    def deconstruct(self):
        name, path, args, kwargs = super(AutoSlugField, self).deconstruct()

        if self.populate_from is not None:
            kwargs['populate_from'] = self.populate_from

        return name, path, args, kwargs

spirit/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from djconfig.forms import ConfigForm


class BasicConfigForm(ConfigForm):

    site_name = forms.CharField(initial="Spirit", label=_("site name"))
    site_description = forms.CharField(initial="", label=_("site description"), max_length=75, required=False)
    template_footer = forms.CharField(initial="", label=_("footer snippet"), required=False,
                                      widget=forms.Textarea(attrs={'rows': 2, }),
                                      help_text=_("This gets rendered just before the footer in your template."))
    comments_per_page = forms.IntegerField(initial=20, label=_("comments per page"), min_value=1, max_value=100)
    topics_per_page = forms.IntegerField(initial=20, label=_("topics per page"), min_value=1, max_value=100)

spirit/category/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import smart_text

from ..models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ("parent", "title", "description", "is_global", "is_closed", "is_removed")

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        queryset = Category.objects.visible().parents()

        if self.instance.pk:
            queryset = queryset.exclude(pk=self.instance.pk)

        self.fields['parent'] = forms.ModelChoiceField(queryset=queryset, required=False)
        self.fields['parent'].label_from_instance = lambda obj: smart_text(obj.title)

    def clean_parent(self):
        parent = self.cleaned_data["parent"]

        if self.instance.pk:
            has_childrens = self.instance.category_set.all().exists()

            if parent and has_childrens:
                raise forms.ValidationError(_("The category you are updating "
                                              "can not have a parent since it has childrens"))

        return parent

spirit/comment/bookmark/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms

from .models import CommentBookmark


class BookmarkForm(forms.ModelForm):

    class Meta:
        model = CommentBookmark
        fields = ['comment_number', ]

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super(BookmarkForm, self).__init__(*args, **kwargs)
        self.user = user
        self.topic = topic

    def save(self, commit=True):
        comment_number = self.cleaned_data['comment_number']

        # Bookmark is created/updated on topic view.
        CommentBookmark.objects\
            .filter(user=self.user, topic=self.topic)\
            .update(comment_number=comment_number)

spirit/comment/flag/admin/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms

from ..models import CommentFlag


class CommentFlagForm(forms.ModelForm):

    class Meta:
        model = CommentFlag
        fields = ("is_closed", )

    def __init__(self, user=None, *args, **kwargs):
        super(CommentFlagForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        self.instance.moderator = self.user
        return super(CommentFlagForm, self).save(commit)

spirit/comment/flag/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError
from django.utils import timezone

from .models import Flag, CommentFlag


class FlagForm(forms.ModelForm):

    class Meta:
        model = Flag
        fields = ['reason', 'body']

    def __init__(self, user=None, comment=None, *args, **kwargs):
        super(FlagForm, self).__init__(*args, **kwargs)
        self.user = user
        self.comment = comment

    def clean(self):
        cleaned_data = super(FlagForm, self).clean()

        flag = Flag.objects.filter(user=self.user,
                                   comment=self.comment)

        if flag.exists():
            # Do this since some of the unique_together fields are excluded.
            raise forms.ValidationError(_("This flag already exists"))

        return cleaned_data

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.comment = self.comment

            try:
                CommentFlag.objects.update_or_create(comment=self.comment,
                                                     defaults={'date': timezone.now(), })
            except IntegrityError:
                pass

        return super(FlagForm, self).save(commit)

spirit/core/templates/spirit/_base.html
{% load spirit_tags i18n %}
{% load static from staticfiles %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock %} - {{ config.site_name }}</title>
    <meta name="description" content="{{ config.site_description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static "spirit/stylesheets/styles.all.min.css" %}">
    <link rel="stylesheet" href="{% static "spirit/stylesheets/my_stylez_spirit.css" %}">

    <script src="{% static "spirit/scripts/all.min.js" %}"></script>

    <script>

	$( document ).ready(function() {

        $.tab();

        $( 'a.js-post' ).postify( {
            csrfToken: "{{ csrf_token }}",
        } );

        $('.js-messages').messages();

        {% if user.is_authenticated %}
            $.notification( {
                notificationUrl: "{% url "spirit:topic:notification:index-ajax" %}",
                notificationListUrl: "{% url "spirit:topic:notification:index-unread" %}",
                mentionTxt: "{% trans "{user} has mention you on {topic}" %}",
                commentTxt: "{% trans "{user} has commented on {topic}" %}",
                showAll: "{% trans "Show all" %}",
                empty: "{% trans "No new notifications, yet" %}",
                unread: "{% trans "unread" %}",
            } );
        {% endif %}

	});

	</script>

    {% block head-extra %}{% endblock %}

    <!--[if (lt IE 9) & (!IEMobile)]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6/html5shiv.min.js"></script>
    <![endif]-->

  </head>

  <body>

    {% include 'spirit/_header.html' %}
    {% render_messages messages %}
    {% block content %}{% endblock %}
    {% include 'spirit/_footer.html' %}

  </body>

</html>

spirit/core/templates/spirit/_footer.html
{{ config.template_footer|safe }}

    <footer class="footer">
		<div class="footer-container">
			<a class="footer-logo" href="http://www.spirit-project.com" >Spirit</a>
		</div>
	</footer>

spirit/core/templates/spirit/_form.html
{% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

{{ form.non_field_errors }}

{% for field in form.hidden_fields %}
    {{ field.errors }}
    {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
    <div class="field">
        {{ field.label_tag }}
        {{ field.errors }}
        {{ field }}
        {{ field.help_text }}
    </div>
{% endfor %}

spirit/core/templates/spirit/_formset.html
{{ formset.management_form }}
{{ formset.non_form_errors }}

{% for f in formset %}
    {% include "spirit/_form.html" with form=f %}
{% endfor %}

spirit/core/templates/spirit/_header.html
{% load spirit_tags i18n %}

    <header class="header js-tabs-container">
		<a class="header-logo" href="{% url "spirit:index" %}">{{ config.site_name }}</a>

        {% if user.is_authenticated %}
            {% has_topic_notifications user as has_notifications %}

            <ul class="header-tabs">
                <li><a class="header-tab-link js-tab" href="{% url "spirit:search:search" %}" data-related=".js-search-content"><i class="fa fa-search"></i></a></li><!--
             --><li><a class="header-tab-link js-tab-notification{% if has_notifications %} is-highlighted{% endif %}" href="{% url "spirit:topic:notification:index" %}" data-related=".js-notifications-content"><i class="fa fa-bell"></i></a></li><!--
             --><li><a class="header-tab-link js-tab" href="{% url "spirit:user:menu" %}" data-related=".js-user-content">{{ user.username }} <i class="fa fa-chevron-down"></i></a></li>
            </ul>

            <div class="header-tabs-content">

                <div class="header-tab-content js-tab-content js-user-content">
                    <nav class="header-nav">
                        <ul class="menu">
                            <li><a class="menu-link" href="{% url "landingpage:landingpage" %}"><strong>Zurück zur Hompage</strong></a></li>
                            <li><a class="menu-link" href="{% url "spirit:user:detail" pk=user.pk slug=user.st.slug %}">{% trans "Profile" %}</a></li>
                            <li><a class="menu-link" href="{% url "spirit:topic:index-active" %}">{% trans "Topics" %}</a></li>
                            <li><a class="menu-link" href="{% url "spirit:topic:unread:index" %}">{% trans "Unread topics" %}</a></li>
                            <li><a class="menu-link" href="{% url "spirit:topic:private:index" %}">{% trans "Private topics" %}</a></li>

                            {% if user.st.is_administrator %}
                                <li><a class="menu-link" href="{% url "spirit:admin:index" %}">{% trans "Admin" %}</a></li>
                            {% endif %}

                            <li><a class="menu-link js-post" href="{% url "spirit:user:auth:logout" %}?next={% firstof request.get_full_path|urlencode '/' %}">{% trans "Log out" %}</a></li>
                        </ul>
                    </nav>
                </div>

                <div class="header-tab-content js-tab-content js-notifications-content"></div>

                <div class="header-tab-content js-tab-content js-search-content">
                    {% render_search_form %}
                </div>

            </div>
        {% else %}
            <a class="header-link" href="{% url "spirit:user:auth:login" %}?next={% firstof request.get_full_path|urlencode '/' %}">{% trans "Log in" %}</a>
        {% endif %}
	</header>